// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Feed struct {
	ID                 int64          `json:"id"`
	Url                string         `json:"url"`
	Title              string         `json:"title"`
	Description        string         `json:"description"`
	LastUpdated        sql.NullTime   `json:"last_updated"`
	LastError          sql.NullString `json:"last_error"`
	LastErrorTime      sql.NullTime   `json:"last_error_time"`
	Visible            bool           `json:"visible"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	Etag               sql.NullString `json:"etag"`
	LastModified       sql.NullString `json:"last_modified"`
	CacheControlMaxAge sql.NullInt64  `json:"cache_control_max_age"`
}

type Item struct {
	ID          int64        `json:"id"`
	FeedID      int64        `json:"feed_id"`
	Guid        string       `json:"guid"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Content     string       `json:"content"`
	Link        string       `json:"link"`
	Published   sql.NullTime `json:"published"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type LogMessage struct {
	ID         int64          `json:"id"`
	Level      string         `json:"level"`
	Message    string         `json:"message"`
	Timestamp  sql.NullTime   `json:"timestamp"`
	Attributes sql.NullString `json:"attributes"`
}

type ReadStatus struct {
	ID     int64        `json:"id"`
	ItemID int64        `json:"item_id"`
	Read   bool         `json:"read"`
	ReadAt sql.NullTime `json:"read_at"`
}

type Setting struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
