[tools]
golang = "1.25.1"
golangci-lint = "2.5.0"
shellcheck = "0.11.0"
nodejs = "22.20.0"
shfmt = "3.12.0"
vale = "3.3.0"

[tasks.golangci-lint]
run = "golangci-lint run ./..."

[tasks.build]
run = """
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "dev")
go build -ldflags "-w -X github.com/jarv/newsgoat/internal/version.GitHash=${GIT_HASH}" -o newsgoat
"""

[tasks.run]
sources =[
  '**/*',
]
run = "go run ."

[tasks.build-release]
run = """
VERSION="{{arg(i=0, default='dev')}}"
LDFLAGS="-w -X github.com/jarv/newsgoat/internal/version.GitHash=v${VERSION}"

# Linux builds (no CGO needed with ncruces/go-sqlite3)
GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS" -o newsgoat-linux-amd64 .
GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o newsgoat-linux-arm64 .

# macOS builds
GOOS=darwin GOARCH=amd64 go build -ldflags "$LDFLAGS" -o newsgoat-darwin-amd64 .
GOOS=darwin GOARCH=arm64 go build -ldflags "$LDFLAGS" -o newsgoat-darwin-arm64 .

# Create checksums
sha256sum newsgoat-* > checksums.txt
"""
