name: Renovate

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.17
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN_NEWSGOAT }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
